/**
 * NINJA TRIALS: BODY, BRAIN & SONIC CHALLENGES (HARD MODE)
 * Comprehensive 7-Stage Curriculum & Challenge Bank
 * CEFR A1–A1+ | Grade 3–4 Physical & Sonic CLIL (Ages 7–11) • 70 min (2-Lesson)
 */

(function(root) {
  'use strict';

  const NINJA_TRIALS_DATA = {
    meta: {
      id: "ninja-trials",
      title: "🥋 Ninja Trials: Body, Brain & Sonic Challenges (Hard Mode)",
      subtitle: "Kinesthetic Action, Decibel Stealth, Sound Mimicry & Tongue Twister Sprints",
      category: "Language & Quests",
      track: "Track 3: Language & Kinesthetic Quests",
      grade: "Grade 3–4",
      level: "CEFR A1–A1+",
      duration: "70 min (2 Lessons)",
      totalStages: 7,
      totalXP: 200,
      safetyDirective: "Strict classroom ergonomics: no backflips, handstands, splits, or cartwheels. Focus on balance, proprioception, speed, volume control, and motor memory."
    },

    stages: [
      { id: 1, name: "Dojo Scanner", title: "Stage 1: Holographic Dojo Scanner", icon: "🔍", badge: "Explorer Badge", xp: 20 },
      { id: 2, name: "Kinetic Arena", title: "Stage 2: Kinetic Reaction Arena", icon: "⏱️", badge: "Reaction Badge", xp: 35 },
      { id: 3, name: "Brain + Body", title: "Stage 3: Brain + Body Combinations", icon: "🧠🔥", badge: "Synergy Badge", xp: 35 },
      { id: 4, name: "Sound Mimic", title: "Stage 4: Sound Mimic Echo Chamber", icon: "🔊", badge: "Echo Badge", xp: 30 },
      { id: 5, name: "Stealth Radar", title: "Stage 5: Decibel Stealth Radar", icon: "🤫", badge: "Stealth Badge", xp: 25 },
      { id: 6, name: "Tongue Twisters", title: "Stage 6: Rapid Tongue Twister Speed Run", icon: "⚡", badge: "Speed Badge", xp: 25 },
      { id: 7, name: "Grandmaster", title: "Stage 7: Grandmaster Teleprompter Studio", icon: "🎙️", badge: "Grandmaster Belt", xp: 30 }
    ],

    categories: [
      {
        id: "gymnastics",
        num: 1,
        title: "Gymnastics & Balance",
        icon: "🤸",
        belt: "Green Belt",
        accent: "#10b981",
        accentGlow: "rgba(16, 185, 129, 0.45)",
        mascotName: "Kira the Acrobat",
        mascotRole: "Balance & Proprioception Master",
        mascotImg: "assets/characters/gymnastics_ninja.jpg",
        description: "Master posture, unilateral balance holds, and controlled landings with zero wobble.",
        sentenceFrame: "I can balance on one leg for 15 seconds and touch my toes with straight knees!"
      },
      {
        id: "dance",
        num: 2,
        title: "Ballet & Dance",
        icon: "🩰",
        belt: "Purple Belt",
        accent: "#a855f7",
        accentGlow: "rgba(168, 85, 247, 0.45)",
        mascotName: "Aya the Shadow Dancer",
        mascotRole: "Grace & Sequence Prodigy",
        mascotImg: "assets/characters/dance_ninja.jpg",
        description: "Execute controlled turns, tiptoe walks, and freeze stops on rhythm.",
        sentenceFrame: "I can walk on my tiptoes and freeze in a graceful ballet pose!"
      },
      {
        id: "athletics",
        num: 3,
        title: "Athletic Power",
        icon: "🏃",
        belt: "Crimson Belt",
        accent: "#ef4444",
        accentGlow: "rgba(239, 68, 68, 0.45)",
        mascotName: "Ren the Fire Sprinter",
        mascotRole: "Endurance & Speed Specialist",
        mascotImg: "assets/characters/athletic_ninja.jpg",
        description: "Power through squats, high knees, and explosive jumping circuits.",
        sentenceFrame: "I can do 10 squats and run in place for 20 seconds!"
      },
      {
        id: "ninja",
        num: 4,
        title: "Ninja & Coordination",
        icon: "🥋",
        belt: "Shadow Blue Belt",
        accent: "#38bdf8",
        accentGlow: "rgba(56, 189, 248, 0.45)",
        mascotName: "Jin the Shadow Shinobi",
        mascotRole: "Stealth & Reflex Sentinel",
        mascotImg: "assets/characters/martial_ninja.jpg",
        description: "Practice silent stealth steps, martial combos, and instant whistle freezes.",
        sentenceFrame: "I can move silently like a shadow and freeze when I hear the whistle!"
      },
      {
        id: "brain_body",
        num: 5,
        title: "Brain + Body Combinations",
        icon: "🧠🔥",
        belt: "Gold Belt",
        accent: "#f59e0b",
        accentGlow: "rgba(245, 158, 11, 0.45)",
        mascotName: "Sensei Tanuki",
        mascotRole: "Grandmaster of Mind & Body Synergy",
        mascotImg: "assets/characters/sensei_ninja.jpg",
        description: "Super Hard dual-tasking: sequence multi-step motor actions with oral declarations.",
        sentenceFrame: "I can jump, clap twice, balance on one leg, and say: 'I can do it!'"
      },
      {
        id: "sound_mimic",
        num: 6,
        title: "Sound Mimic Echo Chamber",
        icon: "🔊",
        belt: "Sonic Resonance Belt",
        accent: "#06b6d4",
        accentGlow: "rgba(6, 182, 212, 0.45)",
        mascotName: "Master Kaze",
        mascotRole: "Acoustic Resonance & Kiai Master",
        mascotImg: "assets/characters/sensei_ninja.jpg",
        description: "Explore vocal pitch, resonance, animal mimicry, and explosive kiai shouts.",
        sentenceFrame: "I can make a loud tiger roar and a quiet viper hiss!"
      },
      {
        id: "stealth_twisters",
        num: 7,
        title: "Decibel Stealth & Twisters",
        icon: "🤫",
        belt: "Grandmaster Dragon Belt",
        accent: "#ec4899",
        accentGlow: "rgba(236, 72, 153, 0.45)",
        mascotName: "Shinobi Scribe",
        mascotRole: "Stealth Volume & Phonics Grandmaster",
        mascotImg: "assets/characters/martial_ninja.jpg",
        description: "Master whisper thresholds (<=30 dB), battle cry surges (100 dB), and lightning phonics twisters.",
        sentenceFrame: "Six swift shinobi spin and stop! I can speak fast and clear!"
      }
    ],

    // Complete Challenge Matrix (38 drills across all 7 categories)
    challenges: [
      // ==================== CATEGORY 1: GYMNASTICS & BALANCE ====================
      {
        id: "gym-1",
        categoryId: "gymnastics",
        num: 1,
        title: "One-Leg Balance Hold",
        question: "Can you balance on one leg for 15 seconds?",
        instruction: "Lift your right knee up to hip level. Keep your core tight, arms spread out for wings, and hold still without touching down!",
        type: "timer",
        timerSeconds: 15,
        repCount: null,
        manner: "for 15 seconds",
        verbs: ["balance", "hold"],
        speechPrompt: "Can you balance on one leg for 15 seconds?",
        responseYes: "Yes, I can balance on one leg!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Keep your standing foot flat on the floor. No jumping during the hold."
      },
      {
        id: "gym-2",
        categoryId: "gymnastics",
        num: 2,
        title: "5 Perfect Jumping Jacks",
        question: "Can you do 5 perfect jumping jacks?",
        instruction: "Feet together, hands at sides. Jump your feet wide and clap your hands overhead with straight elbows, then jump back 5 times!",
        type: "count",
        timerSeconds: null,
        repCount: 5,
        manner: "5 perfect times",
        verbs: ["jump", "clap"],
        speechPrompt: "Can you do 5 perfect jumping jacks?",
        responseYes: "Yes, I can do 5 jumping jacks!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Land softly on the balls of your feet."
      },
      {
        id: "gym-3",
        categoryId: "gymnastics",
        num: 3,
        title: "Straight-Knee Toe Touch",
        question: "Can you touch your toes without bending your knees?",
        instruction: "Stand tall, reach up to the ceiling, and hinge slowly at your hips. Reach for your toes and hold for 8 seconds!",
        type: "timer",
        timerSeconds: 8,
        repCount: null,
        manner: "without bending your knees for 8 seconds",
        verbs: ["touch", "bend"],
        speechPrompt: "Can you touch your toes without bending your knees?",
        responseYes: "Yes, I can touch my toes!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Do not bounce. Reach only as far as comfortable."
      },
      {
        id: "gym-4",
        categoryId: "gymnastics",
        num: 4,
        title: "180° Jump & Front Landing",
        question: "Can you jump, turn around, and land facing forward?",
        instruction: "Bend your knees, leap up smoothly, rotate 180 degrees in the air, and stick the landing with two feet planted firmly!",
        type: "action",
        timerSeconds: null,
        repCount: 1,
        manner: "and land facing forward",
        verbs: ["jump", "turn", "land"],
        speechPrompt: "Can you jump, turn around, and land facing forward?",
        responseYes: "Yes, I can jump and turn!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Keep clear space around your desk."
      },
      {
        id: "gym-5",
        categoryId: "gymnastics",
        num: 5,
        title: "5 Continuous Bunny Hops",
        question: "Can you do 5 bunny hops without stopping?",
        instruction: "Keep both feet glued together. Bend knees slightly, tuck your rabbit paws at your chest, and take 5 quick continuous hops forward!",
        type: "count",
        timerSeconds: null,
        repCount: 5,
        manner: "without stopping",
        verbs: ["hop", "stop"],
        speechPrompt: "Can you do 5 bunny hops without stopping?",
        responseYes: "Yes, I can do 5 bunny hops!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Short, controlled hops only."
      },
      {
        id: "gym-6",
        categoryId: "gymnastics",
        num: 6,
        title: "Superhero Balance Pose",
        question: "Can you hold a superhero balance pose for 10 seconds?",
        instruction: "Stand on your left leg, extend your right leg back straight like flying through the clouds, and stretch one fist forward for 10 seconds!",
        type: "timer",
        timerSeconds: 10,
        repCount: null,
        manner: "for 10 seconds",
        verbs: ["hold", "balance"],
        speechPrompt: "Can you hold a superhero balance pose for 10 seconds?",
        responseYes: "Yes, I can hold the superhero pose!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Fix your gaze on a stationary dot in front of you."
      },
      {
        id: "gym-7",
        categoryId: "gymnastics",
        num: 7,
        title: "Line Jump & Twin Landing",
        question: "Can you jump over a line and land with both feet together?",
        instruction: "Find a tile line on the floor. Stand behind it, spring forward over the line, and land like a gymnast with feet locked together!",
        type: "action",
        timerSeconds: null,
        repCount: 1,
        manner: "with both feet together",
        verbs: ["jump", "land"],
        speechPrompt: "Can you jump over a line and land with both feet together?",
        responseYes: "Yes, I can jump and land together!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Land with knees soft and absorbed."
      },
      {
        id: "gym-8",
        categoryId: "gymnastics",
        num: 8,
        title: "Crown Object Head Walk",
        question: "Can you balance a soft object on your head and walk 5 steps?",
        instruction: "Place an eraser or small soft notebook on your head. Look straight ahead with royal posture, and walk 5 slow steady steps without dropping it!",
        type: "count",
        timerSeconds: null,
        repCount: 5,
        manner: "and walk 5 steps",
        verbs: ["balance", "walk"],
        speechPrompt: "Can you balance a soft object on your head and walk 5 steps?",
        responseYes: "Yes, I can balance and walk 5 steps!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Use only soft, safe classroom items."
      },

      // ==================== CATEGORY 2: BALLET & DANCE ====================
      {
        id: "dance-1",
        categoryId: "dance",
        num: 9,
        title: "10 Tiptoe Steps",
        question: "Can you walk on your tiptoes for 10 steps?",
        instruction: "Rise high on the balls of your feet like a graceful ballerina. Walk 10 silent, light steps without letting your heels touch the floor!",
        type: "count",
        timerSeconds: null,
        repCount: 10,
        manner: "for 10 steps",
        verbs: ["walk", "rise"],
        speechPrompt: "Can you walk on your tiptoes for 10 steps?",
        responseYes: "Yes, I can walk on my tiptoes!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Keep your ankles strong and aligned."
      },
      {
        id: "dance-2",
        categoryId: "dance",
        num: 10,
        title: "10-Second Ballet Passé Pose",
        question: "Can you do a ballet pose and hold it for 10 seconds?",
        instruction: "Stand tall. Place the bottom of one foot against your opposite standing knee in a passé pose. Curve your arms overhead in a crown and hold for 10s!",
        type: "timer",
        timerSeconds: 10,
        repCount: null,
        manner: "for 10 seconds",
        verbs: ["pose", "hold"],
        speechPrompt: "Can you do a ballet pose and hold it for 10 seconds?",
        responseYes: "Yes, I can hold a ballet pose!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Hold onto a chair if you feel unsteady."
      },
      {
        id: "dance-3",
        categoryId: "dance",
        num: 11,
        title: "Controlled Pirouette & Freeze",
        question: "Can you do one controlled turn and freeze?",
        instruction: "Push up on the ball of one foot, spin a slow 360-degree circle with control, and freeze like an ice sculpture the moment you finish!",
        type: "freeze",
        timerSeconds: null,
        repCount: 1,
        manner: "and freeze immediately",
        verbs: ["turn", "freeze"],
        speechPrompt: "Can you do one controlled turn and freeze?",
        responseYes: "Yes, I can turn and freeze!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "One single turn only. Do not spin fast."
      },
      {
        id: "dance-4",
        categoryId: "dance",
        num: 12,
        title: "Jump-Turn-Freeze Combo",
        question: "Can you do a small jump, turn, and freeze?",
        instruction: "Leap softly into the air, turn a half-circle, and stick a rock-solid freeze posture with hands out before touching anything!",
        type: "freeze",
        timerSeconds: null,
        repCount: 1,
        manner: "and freeze",
        verbs: ["jump", "turn", "freeze"],
        speechPrompt: "Can you do a small jump, turn, and freeze?",
        responseYes: "Yes, I can jump, turn, and freeze!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Low jumps only."
      },
      {
        id: "dance-5",
        categoryId: "dance",
        num: 13,
        title: "4-Move Dance Sequence Match",
        question: "Can you copy a 4-move dance sequence?",
        instruction: "Watch the pattern: 1) Clap right -> 2) Clap left -> 3) Step back -> 4) Bow with elegance. Repeat it in exact order!",
        type: "sequence",
        timerSeconds: null,
        repCount: 4,
        manner: "in exact order",
        verbs: ["copy", "dance"],
        speechPrompt: "Can you copy a 4-move dance sequence?",
        responseYes: "Yes, I can copy the 4-move sequence!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Keep movements compact."
      },
      {
        id: "dance-6",
        categoryId: "dance",
        num: 14,
        title: "5 Dance Moves Memory Test",
        question: "Can you remember and perform 5 dance moves?",
        instruction: "Memorize: Sway -> Shimmy -> Spin -> High Five -> Statue Freeze! Perform all 5 smoothly from memory!",
        type: "sequence",
        timerSeconds: null,
        repCount: 5,
        manner: "from memory",
        verbs: ["remember", "perform"],
        speechPrompt: "Can you remember and perform 5 dance moves?",
        responseYes: "Yes, I can perform all 5 moves!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Focus on rhythm and memory."
      },

      // ==================== CATEGORY 3: ATHLETIC POWER ====================
      {
        id: "ath-1",
        categoryId: "athletics",
        num: 15,
        title: "10 Power Squats",
        question: "Can you do 10 squats?",
        instruction: "Feet shoulder-width apart. Sit your hips back like sitting in an invisible chair, keep your chest high, and stand tall 10 times!",
        type: "count",
        timerSeconds: null,
        repCount: 10,
        manner: "10 times",
        verbs: ["squat", "sit"],
        speechPrompt: "Can you do 10 squats?",
        responseYes: "Yes, I can do 10 squats!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Do not let knees collapse inward."
      },
      {
        id: "ath-2",
        categoryId: "athletics",
        num: 16,
        title: "20-Second High-Speed Sprint",
        question: "Can you run in place for 20 seconds?",
        instruction: "Pump your elbows forward and back! Pump your feet as fast as a cheetah while staying in your designated square for 20 seconds!",
        type: "timer",
        timerSeconds: 20,
        repCount: null,
        manner: "for 20 seconds",
        verbs: ["run", "sprint"],
        speechPrompt: "Can you run in place for 20 seconds?",
        responseYes: "Yes, I can run in place for 20 seconds!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Stay in your own floor square."
      },
      {
        id: "ath-3",
        categoryId: "athletics",
        num: 17,
        title: "10 High Knees Sprint",
        question: "Can you do 10 high knees?",
        instruction: "Hold your hands palm-down at waist height. Drive your right knee up to hit your hand, then left, counting 1 to 10!",
        type: "count",
        timerSeconds: null,
        repCount: 10,
        manner: "10 times",
        verbs: ["drive", "lift"],
        speechPrompt: "Can you do 10 high knees?",
        responseYes: "Yes, I can do 10 high knees!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Breathe continuously through your nose."
      },
      {
        id: "ath-4",
        categoryId: "athletics",
        num: 18,
        title: "10 Standing Mountain Climbers",
        question: "Can you do 10 mountain-climber movements?",
        instruction: "Reach opposite arm high while driving opposite knee to chest like climbing Mount Everest standing up! Complete 10 reps!",
        type: "count",
        timerSeconds: null,
        repCount: 10,
        manner: "10 times",
        verbs: ["climb", "reach"],
        speechPrompt: "Can you do 10 mountain-climber movements?",
        responseYes: "Yes, I can do mountain climbers!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Standing variation for maximum classroom safety."
      },
      {
        id: "ath-5",
        categoryId: "athletics",
        num: 19,
        title: "10 Side-to-Side Skater Jumps",
        question: "Can you jump side-to-side 10 times without stopping?",
        instruction: "Hop from right foot to left foot sideways like an Olympic ice skater, absorbing each landing softly. 10 jumps without stopping!",
        type: "count",
        timerSeconds: null,
        repCount: 10,
        manner: "10 times without stopping",
        verbs: ["jump", "skate"],
        speechPrompt: "Can you jump side-to-side 10 times without stopping?",
        responseYes: "Yes, I can jump side-to-side 10 times!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Small side jumps only; keep eyes front."
      },
      {
        id: "ath-6",
        categoryId: "athletics",
        num: 20,
        title: "Floor Touch + Jump + Clap (x5)",
        question: "Can you touch the floor, jump up, clap, and repeat 5 times?",
        instruction: "Squat and touch the floor with both hands, spring up, clap your hands overhead, and repeat the circuit 5 full times!",
        type: "count",
        timerSeconds: null,
        repCount: 5,
        manner: "5 times",
        verbs: ["touch", "jump", "clap"],
        speechPrompt: "Can you touch the floor, jump up, clap, and repeat 5 times?",
        responseYes: "Yes, I can touch the floor, jump, and clap!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Bend at your knees, not your lower back."
      },

      // ==================== CATEGORY 4: NINJA & COORDINATION ====================
      {
        id: "nin-1",
        categoryId: "ninja",
        num: 21,
        title: "5 Punches + 5 Knee Strikes",
        question: "Can you do 5 punches + 5 knee lifts?",
        instruction: "Step into a stable horse stance. Throw 5 crisp straight punches into the air, followed by 5 controlled knee lifts with loud ninja focus!",
        type: "count",
        timerSeconds: null,
        repCount: 10,
        manner: "5 punches and 5 knee lifts",
        verbs: ["punch", "lift"],
        speechPrompt: "Can you do 5 punches and 5 knee lifts?",
        responseYes: "Yes, I can do 5 punches and 5 knees!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Keep punches strictly to open air. Never touch anyone."
      },
      {
        id: "nin-2",
        categoryId: "ninja",
        num: 22,
        title: "5-Move Ninja Kata Sequence",
        question: "Can you copy a 5-move ninja sequence?",
        instruction: "Follow the master kata: 1) High Block -> 2) Palm Strike -> 3) Low Block -> 4) Side Step -> 5) Ready Stance!",
        type: "sequence",
        timerSeconds: null,
        repCount: 5,
        manner: "in sequence",
        verbs: ["block", "strike", "step"],
        speechPrompt: "Can you copy a 5-move ninja sequence?",
        responseYes: "Yes, I can copy the 5-move ninja sequence!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Controlled deliberate muscle tension."
      },
      {
        id: "nin-3",
        categoryId: "ninja",
        num: 23,
        title: "Silent Shadow Stealth Walk",
        question: "Can you move silently across the room?",
        instruction: "Roll your feet from heel to outer toe. Take 8 stealth ninja steps with ZERO sound on the floorboards!",
        type: "action",
        timerSeconds: null,
        repCount: 8,
        manner: "silently across the room",
        verbs: ["move", "glide"],
        speechPrompt: "Can you move silently across the room?",
        responseYes: "Yes, I can move silently!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Keep slow deliberate pace."
      },
      {
        id: "nin-4",
        categoryId: "ninja",
        num: 24,
        title: "Referee Whistle Freeze Reflex",
        question: "Can you freeze immediately when the teacher says STOP?",
        instruction: "Jog lightly in place. The instant you hear the sharp ninja whistle blow, freeze like a stone statue in mid-stride!",
        type: "freeze",
        timerSeconds: null,
        repCount: 1,
        manner: "immediately when the whistle blows",
        verbs: ["freeze", "stop"],
        speechPrompt: "Can you freeze immediately when the whistle sounds?",
        responseYes: "Yes, I can freeze immediately!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Do not wobble, blink, or laugh during the freeze."
      },
      {
        id: "nin-5",
        categoryId: "ninja",
        num: 25,
        title: "Kick + Turn + Superhero Pose",
        question: "Can you do a kick + turn + superhero pose?",
        instruction: "Gentle low kick to waist height, smooth 180-degree spin on the ball of your foot, and land into a majestic superhero stance!",
        type: "action",
        timerSeconds: null,
        repCount: 1,
        manner: "in one smooth combo",
        verbs: ["kick", "turn", "pose"],
        speechPrompt: "Can you do a kick, turn, and superhero pose?",
        responseYes: "Yes, I can do a kick, turn, and pose!",
        responseNo: "No, I can't yet!",
        xp: 15,
        safetyTip: "Low, safe kicks only. Maintain 3 feet clearance."
      },

      // ==================== CATEGORY 5: BRAIN + BODY COMBINATIONS (SUPER HARD) ====================
      {
        id: "combo-1",
        categoryId: "brain_body",
        num: 26,
        title: "Jump -> Clap -> Turn -> Freeze",
        question: "Can you do: Jump -> Clap -> Turn -> Freeze?",
        instruction: "Execute the 4-beat pattern without pausing: First jump up, then clap twice overhead, then turn 180 degrees, and finally freeze like ice!",
        type: "sequence",
        timerSeconds: null,
        repCount: 4,
        manner: "Jump, Clap, Turn, Freeze",
        verbs: ["jump", "clap", "turn", "freeze"],
        speechPrompt: "Can you jump, clap, turn, and freeze?",
        responseYes: "Yes, I can jump, clap, turn, and freeze!",
        responseNo: "No, I can't yet!",
        xp: 20,
        safetyTip: "Lock the freeze for at least 3 seconds."
      },
      {
        id: "combo-2",
        categoryId: "brain_body",
        num: 27,
        title: "Squat -> Double Clap -> Balance -> Speak",
        question: "Can you squat, clap twice, balance, and say 'I can do it!'?",
        instruction: "Squat down low, clap hands twice, stand up onto your right foot in a flamingo balance, and declare loudly: 'I can do it!'",
        type: "sequence",
        timerSeconds: null,
        repCount: 4,
        manner: "with voice declaration",
        verbs: ["squat", "clap", "balance", "say"],
        speechPrompt: "Can you squat, clap twice, balance, and say: 'I can do it!'?",
        responseYes: "Yes! I can do it!",
        responseNo: "No, I can't yet!",
        xp: 20,
        safetyTip: "Clear voice projection during balance."
      },
      {
        id: "combo-3",
        categoryId: "brain_body",
        num: 28,
        title: "Penguin Walk -> Lion Roar -> 3 Jumps",
        question: "Can you walk like a penguin, roar like a lion, and jump 3 times?",
        instruction: "Waddle 5 steps with heels together like a penguin, plant your feet and make a loud fierce lion roar, then do 3 bouncy bunny jumps!",
        type: "sequence",
        timerSeconds: null,
        repCount: 3,
        manner: "animal hybrid sequence",
        verbs: ["walk", "roar", "jump"],
        speechPrompt: "Can you walk like a penguin, roar like a lion, and jump 3 times?",
        responseYes: "Yes, I can do the animal combo!",
        responseNo: "No, I can't yet!",
        xp: 20,
        safetyTip: "Expressive acting and clean transitions."
      },
      {
        id: "combo-4",
        categoryId: "brain_body",
        num: 29,
        title: "5 Jumps -> Turn -> 3 Claps -> Freeze",
        question: "Can you jump 5 times, turn, clap 3 times, and freeze?",
        instruction: "Count aloud: 1-2-3-4-5 jumps! Quick half spin! Clap 1-2-3! FREEZE instantly before taking a breath!",
        type: "sequence",
        timerSeconds: null,
        repCount: 4,
        manner: "with counting and freeze",
        verbs: ["jump", "turn", "clap", "freeze"],
        speechPrompt: "Can you jump 5 times, turn, clap 3 times, and freeze?",
        responseYes: "Yes, I can do the rhythm combo!",
        responseNo: "No, I can't yet!",
        xp: 20,
        safetyTip: "Hold statue pose for 3 seconds."
      },
      {
        id: "combo-5",
        categoryId: "brain_body",
        num: 30,
        title: "One-Leg 10s -> Switch Legs Seamlessly",
        question: "Can you balance on one leg, count to 10, and switch legs?",
        instruction: "Balance on right foot while counting aloud 1 to 10. At 'ten', hop directly to your left foot and count 10 more without touching the floor between!",
        type: "timer",
        timerSeconds: 20,
        repCount: null,
        manner: "with seamless switch",
        verbs: ["balance", "count", "switch"],
        speechPrompt: "Can you balance on one leg, count to 10, and switch legs?",
        responseYes: "Yes, I can balance and switch legs!",
        responseNo: "No, I can't yet!",
        xp: 20,
        safetyTip: "Keep a chair nearby for safety."
      },
      {
        id: "combo-6",
        categoryId: "brain_body",
        num: 31,
        title: "3 Squats -> 3 Jumps -> Hero Pose -> 'I Can Do It!'",
        question: "Can you do 3 squats, 3 jumps, a superhero pose, and say: 'I can do it!'?",
        instruction: "Deep power circuit: 1-2-3 squats, 1-2-3 leaps, stick a dynamic comic superhero pose, and shout: 'I can do it!' with pure confidence!",
        type: "sequence",
        timerSeconds: null,
        repCount: 4,
        manner: "power graduation circuit",
        verbs: ["squat", "jump", "pose", "say"],
        speechPrompt: "Can you do 3 squats, 3 jumps, a superhero pose, and say: 'I can do it!'?",
        responseYes: "Yes! I can do it!",
        responseNo: "No, I can't yet!",
        xp: 20,
        safetyTip: "Strong posture throughout."
      },
      {
        id: "combo-7",
        categoryId: "brain_body",
        num: 32,
        title: "Crab Walk -> Stand -> Spin -> Lion Roar",
        question: "Can you walk like a crab, stand up, spin once, and make a lion sound?",
        instruction: "Squat down and take 4 sideways crab steps with clicking claws, stand up tall, spin 360 degrees, and unleash a mighty lion roar!",
        type: "sequence",
        timerSeconds: null,
        repCount: 4,
        manner: "crab and lion coordination",
        verbs: ["walk", "stand", "spin", "roar"],
        speechPrompt: "Can you walk like a crab, stand up, spin once, and make a lion sound?",
        responseYes: "Yes, I can do the crab and lion combo!",
        responseNo: "No, I can't yet!",
        xp: 20,
        safetyTip: "Take care when standing up quickly."
      },
      {
        id: "combo-8",
        categoryId: "brain_body",
        num: 33,
        title: "Master Kata: 5-Move Sequence Zero Mistakes",
        question: "Can you copy the teacher's 5-move sequence without mistakes?",
        instruction: "Final Grandmaster Trial: 1) High Block -> 2) Low Punch -> 3) Double Clap -> 4) Turn Right -> 5) Bow and say: 'I am a Ninja!'",
        type: "sequence",
        timerSeconds: null,
        repCount: 5,
        manner: "without mistakes",
        verbs: ["block", "punch", "clap", "turn", "bow"],
        speechPrompt: "Can you copy the teacher's 5-move sequence without mistakes?",
        responseYes: "Yes! I am a Ninja!",
        responseNo: "No, I can't yet!",
        xp: 25,
        safetyTip: "Solemn graduation focus and martial discipline."
      },

      // ==================== CATEGORY 6: 🔊 SOUND MIMIC ECHO CHAMBER ====================
      {
        id: "sound-1",
        categoryId: "sound_mimic",
        num: 34,
        title: "Tiger Roar (Acoustic Resonance)",
        question: "Can you make a resonant Tiger Roar with a claw strike?",
        instruction: "Step forward into a cat stance. Drop your voice into chest resonance (low pitch), sweep claw hands across, and roar: 'ROAARRR!'",
        type: "sound_mimic",
        soundType: "roar",
        manner: "low-frequency resonant roar + claw strike",
        verbs: ["roar", "strike"],
        speechPrompt: "Can you make a resonant tiger roar with a claw strike?",
        responseYes: "Yes! ROAARRR! I can roar like a tiger!",
        responseNo: "No, I can't yet!",
        xp: 20,
        safetyTip: "Use vocal cords gently with diaphragmatic breath."
      },
      {
        id: "sound-2",
        categoryId: "sound_mimic",
        num: 35,
        title: "Viper Hiss (Sustained /s/ Exhale)",
        question: "Can you balance on one leg and sustain a Viper Hiss for 8 seconds?",
        instruction: "Stand on one leg in a serpent pose. Inhale deeply and release a narrow, continuous, razor-sharp /s-s-s-s/ hiss for 8 seconds!",
        type: "sound_mimic",
        soundType: "hiss",
        timerSeconds: 8,
        manner: "continuous /s/ hiss on one leg",
        verbs: ["hiss", "balance"],
        speechPrompt: "Can you balance on one leg and hiss like a viper?",
        responseYes: "Yes! Ssssss! I can hiss like a viper!",
        responseNo: "No, I can't yet!",
        xp: 20,
        safetyTip: "Exhale smoothly without running out of air abruptly."
      },
      {
        id: "sound-3",
        categoryId: "sound_mimic",
        num: 36,
        title: "Lightning Kiai (Martial Snap Shout)",
        question: "Can you throw a punch and shout a sharp 'EI-YA!' kiai?",
        instruction: "Horse stance! Chamber your fist at your ribs. Punch straight out with explosive speed and snap an authentic ninja kiai: 'EI-YA!'",
        type: "sound_mimic",
        soundType: "kiai",
        manner: "sharp punch + 'EI-YA!' kiai shout",
        verbs: ["punch", "shout"],
        speechPrompt: "Can you throw a punch and shout a sharp EI-YA kiai?",
        responseYes: "EI-YA! Yes, I can shout the kiai!",
        responseNo: "No, I can't yet!",
        xp: 20,
        safetyTip: "Short, sharp vocal burst from the belly."
      },

      // ==================== CATEGORY 7: 🤫 DECIBEL STEALTH & TONGUE TWISTERS ====================
      {
        id: "stealth-1",
        categoryId: "stealth_twisters",
        num: 37,
        title: "Stealth Whisper Threshold (<= 30 dB)",
        question: "Can you walk across the room whispering under 30 decibels?",
        instruction: "Creep on tiptoes across the floor. Whisper softly: 'I can move silently, I am a shadow ninja.' Keep your volume needle in the Green Stealth Zone!",
        type: "decibel_stealth",
        decibelTarget: 30,
        manner: "under 30 decibels on tiptoes",
        verbs: ["whisper", "creep"],
        speechPrompt: "Can you whisper under 30 decibels on tiptoes?",
        responseYes: "Shhh... yes, I can move under thirty decibels!",
        responseNo: "No, I was too loud!",
        xp: 20,
        safetyTip: "Watch where you step while looking down."
      },
      {
        id: "stealth-2",
        categoryId: "stealth_twisters",
        num: 38,
        title: "Ninja Battle Cry Surge (100 dB Surge)",
        question: "Can you take a power stance and surge the meter with 'I CAN DO IT!'?",
        instruction: "Drop into a wide warrior stance. On the count of 3, shout together with your class: 'I CAN DO IT!' to surge the decibel meter to 100%!",
        type: "decibel_surge",
        decibelTarget: 95,
        manner: "full class power surge",
        verbs: ["shout", "surge"],
        speechPrompt: "Can you shout 'I CAN DO IT!' and surge the meter?",
        responseYes: "I CAN DO IT! 100% Power!",
        responseNo: "No, need more energy!",
        xp: 20,
        safetyTip: "Stand firmly with feet shoulder-width apart."
      },
      {
        id: "twister-1",
        categoryId: "stealth_twisters",
        num: 39,
        title: "Phonics Twister 1: Swift Shinobi (/s/ & /st/)",
        question: "Can you say: 'Six swift shinobi spin and stop!' 3 times fast?",
        instruction: "Speed tongue twister! Place your tongue behind your top teeth. Repeat 3 times without stumbling: 'Six swift shinobi spin and stop!'",
        type: "tongue_twister",
        phonicsSound: "/s/ and /st/",
        phrase: "Six swift shinobi spin and stop!",
        timerSeconds: 15,
        manner: "3 times in 15 seconds",
        verbs: ["spin", "stop"],
        speechPrompt: "Can you say: 'Six swift shinobi spin and stop' three times fast?",
        responseYes: "Six swift shinobi spin and stop! Yes, I can!",
        responseNo: "No, my tongue got twisted!",
        xp: 20,
        safetyTip: "Clear articulation is better than rushed mumbling."
      },
      {
        id: "twister-2",
        categoryId: "stealth_twisters",
        num: 40,
        title: "Phonics Twister 2: Fierce Foxes (/f/ on 1 Foot)",
        question: "Can you balance on 1 foot and say: 'Five fierce foxes freeze on frozen feet!'?",
        instruction: "Stand on your left foot in a flamingo pose. Say clearly: 'Five fierce foxes freeze on frozen feet!' without wobbling down!",
        type: "tongue_twister",
        phonicsSound: "/f/ and /fr/",
        phrase: "Five fierce foxes freeze on frozen feet!",
        timerSeconds: 15,
        manner: "on one foot",
        verbs: ["freeze", "balance"],
        speechPrompt: "Can you balance on one foot and say: 'Five fierce foxes freeze on frozen feet'?",
        responseYes: "Five fierce foxes freeze on frozen feet! Yes, I can!",
        responseNo: "No, I lost my balance!",
        xp: 20,
        safetyTip: "Focus eyes on a single dot in front of you."
      },
      {
        id: "twister-3",
        categoryId: "stealth_twisters",
        num: 41,
        title: "Phonics Twister 3: Quick Kick (/k/ & /p/ Snap)",
        question: "Can you do: 'Quick kick, click clap, stick and snap!' with actions?",
        instruction: "Perform with physical actions: Low kick ('Quick kick'), Click fingers ('click'), Clap hands ('clap'), Freeze statue ('stick'), Snap fingers ('and snap!')!",
        type: "tongue_twister",
        phonicsSound: "/k/ and /p/",
        phrase: "Quick kick, click clap, stick and snap!",
        timerSeconds: 15,
        manner: "with matching physical actions",
        verbs: ["kick", "clap", "snap"],
        speechPrompt: "Can you do: 'Quick kick, click clap, stick and snap' with actions?",
        responseYes: "Quick kick, click clap, stick and snap! Mastered!",
        responseNo: "No, need another try!",
        xp: 20,
        safetyTip: "Gentle low kick only."
      }
    ],

    // Oral Teleprompter Graduation Showcase Templates (3-Sentence Production Ceiling)
    teleprompterTemplates: [
      {
        id: "tp-gymnastics",
        title: "Gymnastics & Balance Showcase",
        category: "gymnastics",
        mascotImg: "assets/characters/gymnastics_ninja.jpg",
        line1: "Welcome to Adventure Academy! Today I completed the kinetic balance trials.",
        line2: "I can balance on one leg for 15 seconds and touch my toes with straight knees!",
        line3: "Challenge complete — I can do it!"
      },
      {
        id: "tp-dance",
        title: "Ballet & Dance Showcase",
        category: "dance",
        mascotImg: "assets/characters/dance_ninja.jpg",
        line1: "Welcome to Adventure Academy! Today I completed the grace and rhythm trials.",
        line2: "I can walk on my tiptoes and freeze in a graceful ballet pose!",
        line3: "Challenge complete — I can do it!"
      },
      {
        id: "tp-athletics",
        title: "Athletic Power Showcase",
        category: "athletics",
        mascotImg: "assets/characters/athletic_ninja.jpg",
        line1: "Welcome to Adventure Academy! Today I completed the high-speed sprint trials.",
        line2: "I can do 10 squats and run in place for 20 seconds!",
        line3: "Challenge complete — I can do it!"
      },
      {
        id: "tp-ninja",
        title: "Shinobi Coordination Showcase",
        category: "ninja",
        mascotImg: "assets/characters/martial_ninja.jpg",
        line1: "Welcome to Adventure Academy! Today I completed the stealth ninja trials.",
        line2: "I can move silently like a shadow and freeze when I hear the whistle!",
        line3: "Challenge complete — I can do it!"
      },
      {
        id: "tp-brain-body",
        title: "Brain + Body Synergy Showcase",
        category: "brain_body",
        mascotImg: "assets/characters/sensei_ninja.jpg",
        line1: "Welcome to Adventure Academy! Today I mastered the multi-action memory chains.",
        line2: "First I jumped, then I clapped twice, and finally I froze like a master!",
        line3: "Challenge complete — I can do it!"
      },
      {
        id: "tp-sonic",
        title: "Sound Mimic & Kiai Showcase",
        category: "sound_mimic",
        mascotImg: "assets/characters/sensei_ninja.jpg",
        line1: "Welcome to Adventure Academy! Today I mastered the acoustic echo chamber.",
        line2: "I can roar like a tiger, hiss like a viper, and shout a sharp kiai!",
        line3: "Challenge complete — I can do it!"
      },
      {
        id: "tp-stealth-twisters",
        title: "Decibel Stealth & Speed Twister Showcase",
        category: "stealth_twisters",
        mascotImg: "assets/characters/martial_ninja.jpg",
        line1: "Welcome to Adventure Academy! Today I mastered stealth volume and speed twisters.",
        line2: "Six swift shinobi spin and stop — I can whisper quietly and shout with power!",
        line3: "Challenge complete — I can do it!"
      }
    ]
  };

  root.NINJA_TRIALS_DATA = NINJA_TRIALS_DATA;

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = NINJA_TRIALS_DATA;
  }
})(typeof window !== 'undefined' ? window : global);
