/* Simon Says: command banks by grade.
   Grade 3 (A1): Unit 1 inventions + phonics review, monster body parts (Monster Day), Unit 2 harvest / Chuseok / Mars.
   Grade 4 (A1+): Unit 1 Alice + the brain + reading, Unit 2 forests / animals / A New Friend, spelling pattern ai.
   Fields: c = category, t = the command (what Simon says), i = big picture, l = level (1 easy, 2 medium, 3 combo). */
var SIMON = {
  3: {
    name: 'Grade 3',
    sub: 'Inventors · Monsters · Harvest',
    cats: {
      invent:  {label: 'Inventors',      icon: '🔧', color: '#3b82f6'},
      monster: {label: 'Monster parts',  icon: '👹', color: '#8b5cf6'},
      sounds:  {label: 'Sound moves',    icon: '🔊', color: '#f59e0b'},
      harvest: {label: 'Harvest & Mars', icon: '🌾', color: '#16a34a'},
      move:    {label: 'Class moves',    icon: '🏫', color: '#ec4899'}
    },
    cmds: [
      {c:'invent', t:'plan your invention', i:'📝', l:1},
      {c:'invent', t:'build a machine', i:'🔨', l:1},
      {c:'invent', t:'test your machine', i:'🔘', l:1},
      {c:'invent', t:'press the button', i:'🔴', l:1},
      {c:'invent', t:'try again', i:'🔁', l:1},
      {c:'invent', t:'change your machine', i:'🔧', l:1},
      {c:'invent', t:'tidy your desk', i:'🧹', l:1},
      {c:'invent', t:'make a mess', i:'🌪️', l:1},
      {c:'invent', t:'look in the mirror', i:'🪞', l:1},
      {c:'invent', t:'invent something new', i:'💡', l:2},
      {c:'invent', t:'open your parachute', i:'🪂', l:2},
      {c:'invent', t:'cheer, it works', i:'🎉', l:2},
      {c:'invent', t:'First plan. Second build. Third test. Last cheer.', i:'🧪', l:3},
      {c:'invent', t:'First press the button. Then try again.', i:'🔴', l:3},
      {c:'monster', t:'wiggle your tail', i:'🦎', l:1},
      {c:'monster', t:'show your claws', i:'🐾', l:1},
      {c:'monster', t:'open your eyes wide', i:'👀', l:1},
      {c:'monster', t:'show your fangs', i:'🦷', l:1},
      {c:'monster', t:'flap your wings', i:'🦇', l:1},
      {c:'monster', t:'touch your horns', i:'🦄', l:1},
      {c:'monster', t:'roar like a monster', i:'👹', l:1},
      {c:'monster', t:'walk like a big monster', i:'🦖', l:2},
      {c:'monster', t:'Show your claws. Then roar.', i:'🐾', l:3},
      {c:'sounds', t:'stand up fast', i:'⚡', l:1},
      {c:'sounds', t:'stamp your feet', i:'🥁', l:1},
      {c:'sounds', t:'stir the soup', i:'🥣', l:1},
      {c:'sounds', t:'stretch your arms', i:'🙆', l:1},
      {c:'sounds', t:'shake your hands', i:'🙌', l:1},
      {c:'sounds', t:'shut your eyes', i:'😌', l:1},
      {c:'sounds', t:'flap your arms', i:'🐦', l:1},
      {c:'sounds', t:'freeze', i:'🧊', l:1},
      {c:'sounds', t:'hop like a frog', i:'🐸', l:1},
      {c:'sounds', t:'fly a kite', i:'🪁', l:2},
      {c:'sounds', t:'Stand up fast. Then stamp your feet.', i:'⚡', l:3},
      {c:'harvest', t:'pick the fruit', i:'🍎', l:1},
      {c:'harvest', t:'dig up the vegetables', i:'🥔', l:1},
      {c:'harvest', t:'water the plants', i:'🚿', l:1},
      {c:'harvest', t:'grow like a seed', i:'🌱', l:2},
      {c:'harvest', t:'weave your fingers', i:'🧶', l:2},
      {c:'harvest', t:'bow to your ancestors', i:'🙇', l:2},
      {c:'harvest', t:'dance in a circle', i:'💃', l:1},
      {c:'harvest', t:'make a half moon with your hands', i:'🌙', l:2},
      {c:'harvest', t:'eat a songpyeon. Yum', i:'🥟', l:1},
      {c:'harvest', t:'put on your space suit', i:'👨‍🚀', l:1},
      {c:'harvest', t:'check your helmet', i:'🪖', l:1},
      {c:'harvest', t:'say thank you', i:'🙏', l:1},
      {c:'harvest', t:'celebrate the harvest', i:'🎊', l:1},
      {c:'harvest', t:'Put on your space suit. Then check your helmet.', i:'👨‍🚀', l:3},
      {c:'move', t:'clap your hands', i:'👏', l:1},
      {c:'move', t:'stand up', i:'🧍', l:1},
      {c:'move', t:'sit down', i:'🪑', l:1},
      {c:'move', t:'turn around', i:'🔄', l:1},
      {c:'move', t:'jump two times', i:'🦘', l:1},
      {c:'move', t:'touch your toes', i:'🦶', l:1},
      {c:'move', t:'put your hands up', i:'🙌', l:1},
      {c:'move', t:'wave hello', i:'👋', l:1},
      {c:'move', t:'march in place', i:'💂', l:1}
    ]
  },
  4: {
    name: 'Grade 4',
    sub: 'Alice · Brain · Forests',
    cats: {
      alice:  {label: 'Alice',          icon: '🐇', color: '#ec4899'},
      brain:  {label: 'Brain & reading', icon: '🧠', color: '#8b5cf6'},
      forest: {label: 'Forest animals', icon: '🌲', color: '#16a34a'},
      story:  {label: 'A New Friend',   icon: '🐦', color: '#f59e0b'},
      move:   {label: 'Class moves',    icon: '🏫', color: '#3b82f6'}
    },
    cmds: [
      {c:'alice', t:'fall down the rabbit hole', i:'🕳️', l:2},
      {c:'alice', t:'chase the White Rabbit', i:'🐇', l:1},
      {c:'alice', t:'open a book', i:'📖', l:1},
      {c:'alice', t:'turn the page', i:'📄', l:1},
      {c:'alice', t:'yawn. You are sleepy', i:'🥱', l:1},
      {c:'alice', t:'look at the shelves', i:'🗄️', l:1},
      {c:'alice', t:'drink from the little bottle', i:'🧪', l:2},
      {c:'alice', t:'get very small', i:'🔬', l:1},
      {c:'alice', t:'get very tall', i:'🦒', l:1},
      {c:'alice', t:'Fall down. Then chase the rabbit.', i:'🕳️', l:3},
      {c:'alice', t:'Show me how Alice fell. Then show me how she chased the rabbit.', i:'🐇', l:3},
      {c:'brain', t:'visualize. Close your eyes and imagine', i:'🧠', l:2},
      {c:'brain', t:'skim the page. Move your eyes fast', i:'👁️', l:2},
      {c:'brain', t:'think hard', i:'🤔', l:1},
      {c:'brain', t:'give your brain a workout. Run in place', i:'🏃', l:2},
      {c:'brain', t:'send a message. Point to a friend', i:'📨', l:2},
      {c:'brain', t:'be creative. Make a funny shape', i:'🎨', l:2},
      {c:'brain', t:'read quietly', i:'🤫', l:1},
      {c:'brain', t:'Open a book. Then read quietly.', i:'📖', l:3},
      {c:'forest', t:'hibernate like a bear', i:'🐻', l:1},
      {c:'forest', t:'freeze like a hare in the snow', i:'🐇', l:1},
      {c:'forest', t:'shiver. It is very cold', i:'🥶', l:1},
      {c:'forest', t:'tiptoe like a deer', i:'🦌', l:1},
      {c:'forest', t:'howl like a wolf', i:'🐺', l:1},
      {c:'forest', t:'hoot like an owl', i:'🦉', l:1},
      {c:'forest', t:'fall like an autumn leaf', i:'🍂', l:1},
      {c:'forest', t:'stand like a tall pine tree', i:'🌲', l:1},
      {c:'forest', t:'Hide so the wolf cannot see you.', i:'🙈', l:3},
      {c:'forest', t:'Wave with your feet instead of your hands.', i:'🦶', l:3},
      {c:'story', t:'flap like a swallow', i:'🐦', l:1},
      {c:'story', t:'build a nest with your hands', i:'🪹', l:2},
      {c:'story', t:'fix the roof', i:'🏠', l:1},
      {c:'story', t:'pay with gold coins', i:'🪙', l:1},
      {c:'story', t:'take the baby bird to the vet', i:'🩺', l:2},
      {c:'story', t:'help a friend. Be kind', i:'🤝', l:1},
      {c:'story', t:'sail a boat', i:'⛵', l:1},
      {c:'story', t:'wait for the train', i:'🚂', l:1},
      {c:'story', t:'paint a picture', i:'🎨', l:1},
      {c:'story', t:'wag your tail', i:'🐕', l:1},
      {c:'story', t:'Pick up a coin. Then fix the roof.', i:'🪙', l:3},
      {c:'move', t:'clap your hands', i:'👏', l:1},
      {c:'move', t:'stand up', i:'🧍', l:1},
      {c:'move', t:'sit down', i:'🪑', l:1},
      {c:'move', t:'turn around', i:'🔄', l:1},
      {c:'move', t:'jump three times', i:'🦘', l:1},
      {c:'move', t:'touch your toes', i:'🦶', l:1},
      {c:'move', t:'Touch your toes. Then jump once.', i:'⚡', l:3},
      {c:'move', t:'Clap twice. Turn around. Sit down.', i:'👏', l:3}
    ]
  }
};
/* Words that sound like Simon but are NOT Simon: the game uses these as sneaky lead-ins (level 2 and up). */
var SIMON_FAKE = ['Teacher says', 'Simon asks you to', 'Monkey says', 'Please', 'Simone says'];
