/* Unit 1 revision questions (Grade 3 and Grade 4) */
var DATA = {
 3: [
  {s:'Listening', say:'I can see a parachute.', q:'Listen. Which picture?', o:['🪂','🎈','⭐','🪁'], a:'🪂', big:true},
  {s:'Listening', say:'My monster has got big claws.', q:'Listen. Which picture?', o:['👀','🐾','🦷','🐟'], a:'🐾', big:true},
  {s:'Listening', say:'Look at the frog.', q:'Listen. Which picture?', o:['🐟','🏁','🐸','🦆'], a:'🐸', big:true},
  {s:'Listening', say:'This is a kite.', q:'Listen. Which picture?', o:['🪁','🚲','🍰','🎈'], a:'🪁', big:true},
  {s:'Words', q:'My room is a ___. Toys are everywhere!', o:['mess','plan','mirror','hexagon'], a:'mess'},
  {s:'Words', q:'Please ___ your room. Put the toys away.', o:['tidy','invent','mess','try'], a:'tidy'},
  {s:'Words', q:'It doesn’t work. Don’t stop. ___ again!', o:['Try','Sleep','Hide','Close'], a:'Try'},
  {s:'Words', q:'Clara builds a ___ to clean her room.', o:['machine','hexagon','mirror','parachute'], a:'machine'},
  {s:'Words', q:'What does “invent” mean?', o:['make something new','eat your lunch','run very fast','go to sleep'], a:'make something new'},
  {s:'Sentences', q:'My monster ___ three eyes.', o:['has got','have got'], a:'has got'},
  {s:'Sentences', q:'Monsters ___ big claws.', o:['has got','have got'], a:'have got'},
  {s:'Sentences', q:'What ___ the machine do?', o:['do','does'], a:'does'},
  {s:'Sentences', q:'The eraser ___ the paper.', o:['clean','cleans'], a:'cleans'},
  {s:'Sounds', q:'Which word is the picture?', pic:'🚢', o:['chip','ship','sip','hip'], a:'ship'},
  {s:'Sounds', q:'Which word is the picture?', pic:'🐸', o:['frog','frug','flog','prog'], a:'frog'},
  {s:'Sounds', q:'Which word is the picture?', pic:'🪁', o:['kit','kite','kick','kiss'], a:'kite'},
  {s:'Sounds', q:'Which word is the picture?', pic:'🦴', o:['bon','bone','ban','born'], a:'bone'},
  {s:'Reading order', q:'Put the words in order.', order:['First,','Mia','makes','a','plan.']},
  {s:'Reading order', q:'Put the words in order.', order:['Last,','the','machine','works!']},
  {s:'Reading', pass:'Mia has a problem. Her room is a mess. First, she makes a plan. Second, she builds a machine. Last, the machine works!', q:'What is Mia’s problem?', o:['Her room is a mess.','She is hungry.','Her machine is broken.','She has no toys.'], a:'Her room is a mess.'},
  {s:'Reading', pass:'Mia has a problem. Her room is a mess. First, she makes a plan. Second, she builds a machine. Last, the machine works!', q:'What does Mia do second?', o:['She builds a machine.','She makes a plan.','She goes to bed.','She tidies the toys.'], a:'She builds a machine.'}
 ],
 4: [
  {s:'Listening', say:'The caterpillar is on the branch.', q:'Listen. Which picture?', o:['🐛','🦋','🐇','🐝'], a:'🐛', big:true},
  {s:'Listening', say:'Alice chased a White Rabbit.', q:'Listen. Which picture?', o:['🐈','🐇','🐛','🐦'], a:'🐇', big:true},
  {s:'Listening', say:'The monarch butterfly goes on a long journey.', q:'Listen. Which picture?', o:['🐝','🐦','🦋','🐞'], a:'🦋', big:true},
  {s:'Listening', say:'Reading is a workout for your brain.', q:'Listen. Which picture?', o:['🧠','👁️','🦶','👂'], a:'🧠', big:true},
  {s:'Words', q:'A rabbit sees a predator. It stays very still. It can ___.', o:['freeze','visualize','journey','chase'], a:'freeze'},
  {s:'Words', q:'Every year, monarch butterflies go on a long ___.', o:['journey','workout','shelf','corner'], a:'journey'},
  {s:'Words', q:'When I read, I ___ the story. I make pictures in my head.', o:['visualize','freeze','chase','fall'], a:'visualize'},
  {s:'Words', q:'Alice was tired. She was ___.', o:['sleepy','creative','chased','still'], a:'sleepy'},
  {s:'Words', q:'A predator is an animal that ___ other animals.', o:['hunts','paints','reads','sleeps with'], a:'hunts'},
  {s:'Sentences', q:'___ did Alice chase? — A White Rabbit.', o:['Who','Where','When','Why'], a:'Who'},
  {s:'Sentences', q:'___ was Alice sleepy? — Because she was bored.', o:['Why','Who','Where','What'], a:'Why'},
  {s:'Sentences', q:'___ did Alice fall? — Down a deep hole.', o:['Where','Who','Why','Which'], a:'Where'},
  {s:'Sentences', q:'Then Alice ___ the rabbit.', o:['chase','chased','chasing','chases'], a:'chased'},
  {s:'Sentences', q:'Alice ___ down a deep hole.', o:['fall','fell','falled','falling'], a:'fell'},
  {s:'Sounds', q:'Which word ends with -st?', o:['fang','fast','fan','fat'], a:'fast'},
  {s:'Sounds', q:'Which word ends with -nd?', o:['wing','win','wind','wine'], a:'wind'},
  {s:'Sounds', q:'Which word ends with -ng?', o:['long','lost','land','lamp'], a:'long'},
  {s:'Sounds', q:'Which word starts with tr-?', o:['three','free','tree','tea'], a:'tree'},
  {s:'Sounds', q:'A person who reads is a ___.', o:['reader','readed','readest','readly'], a:'reader'},
  {s:'Reading', pass:'Your brain has many cells. These cells send messages to each other. Reading is like a workout for your brain!', q:'What do brain cells send?', o:['messages','letters','pictures','books'], a:'messages'},
  {s:'Reading', pass:'Skimming means looking at the title, the headings and the first sentences before you read.', q:'What is skimming?', o:['Looking at the title and headings first','Reading every word slowly','Reading only the last page','Drawing a picture'], a:'Looking at the title and headings first'},
  {s:'Reading order', q:'Put the words in order.', order:['Alice','chased','the','White','Rabbit.']},
  {s:'Reading order', q:'Put the words in order.', order:['Reading','is','a','workout','for','my','brain.']}
 ]
};
